services:
  postgres:
    image: postgres:15-alpine
    container_name: movierama-postgres
    environment:
      POSTGRES_DB: movierama_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - movierama-network
  
  backend:
    build:
      context: ./backend-rust/movierama
      dockerfile: Dockerfile
    container_name: movierama-backend
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/movierama_db
      JWT_SECRET: "replace-this-with-a-secure-long-secret"
      RUST_LOG: "info"
    depends_on:
      - postgres
    ports:
      - "9000:9000"
    networks:
      - movierama-network
  
  frontend:
    build:
      context: ./frontend/movierama
    container_name: movierama-frontend
    depends_on:
      - backend
    ports:
      - "5173:80"
    networks:
      - movierama-network

volumes:
  postgres_data:

networks:
  movierama-network:
    driver: bridge
    
